[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/web-design-jerusalem"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/בניית-אתרים-ירושלים"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/jerusalem-orm"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/ניהול-מוניטין-בירושלים"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/accessibility"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/privacy-policy"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "max-age=31536000"